### ISSUE TITLE
Invalid s3 file path when generated in Windows environment

### ISSUE THREAD

**Issue by ugnom** [ohbuchim/sample-codes-for-aiml#1]
amazon-sagemaker-ground-truth/scripts/transform_video_manifest_to_image_manifest.py 

こちらのファイルを実行してみたのですが、Windowsで実行すると、source-ref用に生成するs3のpathが不正になる現象を確認しました。
期待するアウトプット：s3://my-bucket-name/folder1/folder2/frame_0001.jpg
確認した現象：s3://my-bucket-name/folder1/folder2\\\\frame_0001.jpg

34行目でs3でpathをくっつけるときにos.path.joinを使っていますが単純に"/"で結合するように変更すれば問題ないように思います。

**Comment by ohbuchim** [comment]
ありがとうございます、コードを修正いたしました。
